version: "3.8"

services:
  db:
    image: postgres
    container_name: todo
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "soro"
      POSTGRES_PASSWORD: "pass123"
      POSTGRES_DB: "todo"
